library(ggplot2)
library(dplyr)
library(Rcpp)
library(readxl)
library(stringr)
library(gcookbook)
library(gridExtra)
library(ggpubr)
library(parallel)


setwd("/home/huanhuan/project/RNA/eQTL_associated_interaction/GTEx/output/Whole_Blood/Cis_eQTL/ROC/interval_18/ALL/split_non_factor/")
org<-read.table("08_prepare_number_ROC_factor_count.txt",header = T,sep = "\t") %>% as.data.frame()
enhancer <-dplyr::filter(org,Factor == "enhancer")
promoter <-dplyr::filter(org,Factor == "promoter")
pdf("enhancer_factor.pdf")
p <-ggplot(enhancer,mapping = aes(x = FPR, y = TPR,colour = Cutoff)) + geom_point(size = 3)+ggtitle("Enhancer")+theme(plot.title = element_text(hjust = 0.5))
print(p)
dev.off()

pdf("promoter_factor.pdf")
p <-ggplot(promoter,mapping = aes(x = FPR, y = TPR,colour = Cutoff)) + geom_point(size = 3)+ggtitle("Promoter")+theme(plot.title = element_text(hjust = 0.5))
print(p)
dev.off()

