ln /home/huanhuan/project/RNA/eQTL_associated_interaction/annotation/annotation_data/CTCF/normal_cell_line/05_normal_cell_line_ctcf_sort.bed.gz CTCF.bed.gz
ln /home/huanhuan/project/RNA/eQTL_associated_interaction/annotation/annotation_data/CTCF/normal_cell_line/split_CTCF_complement.bed.gz  non_CTCF_split.bed.gz

ln /home/huanhuan/project/RNA/eQTL_associated_interaction/annotation/annotation_data/cistromeDB/normal_cell/Human_CHROMATIN_Accessibility/merge_pos_info_narrow_peak_complement_split.bed.gz non_CHROMATIN_Accessibility_split.bed.gz
ln /home/huanhuan/project/RNA/eQTL_associated_interaction/annotation/annotation_data/cistromeDB/normal_cell/Human_CHROMATIN_Accessibility/merge_pos_info_narrow_peak_sort.bed.gz CHROMATIN_Accessibility.bed.gz

ln /home/huanhuan/project/RNA/eQTL_associated_interaction/annotation/annotation_data/cistromeDB/normal_cell/HISTONE_MARK_AND_VARIANT/merge_pos_info_narrow_peak_complement_split.bed.gz non_HISTONE_modification_split.bed.gz
ln /home/huanhuan/project/RNA/eQTL_associated_interaction/annotation/annotation_data/cistromeDB/normal_cell/HISTONE_MARK_AND_VARIANT/merge_pos_info_narrow_peak_sort.bed.gz HISTONE_modification.bed.gz

ln /home/huanhuan/project/RNA/eQTL_associated_interaction/annotation/annotation_data/cistromeDB/normal_cell/Human_FACTOR/merge_pos_info_narrow_peak_sort.bed.gz TFBS.bed.gz
ln /home/huanhuan/project/RNA/eQTL_associated_interaction/annotation/annotation_data/cistromeDB/normal_cell/Human_FACTOR/merge_pos_info_narrow_peak_complement_split.bed.gz non_TFBS_split.bed.gz



