# perl 08_count_factor_and_non_factor_annotation_interval18_different_cutoff.pl
# echo -e "08_count_factor_and_non_factor_annotation_interval18_different_cutoff\n"
# Rscript 10_plot_point_factor_non_factor.R
# echo -e "10_plot_point_factor_non_factor\n"
# Rscript 10_fisher_exact_test_factor_and_non_factor.R
# echo -e "10_fisher_exact_test_factor_and_non_factor\n"
perl  07_annotation_non_factor_split_interval_18_different_cutoff_re.pl
echo -e "07_annotation_non_factor_split_interval_18_different_cutoff_re\n"
perl 08_count_factor_and_non_factor_annotation_interval18_different_cutoff_re.pl
echo -e "08_count_factor_and_non_factor_annotation_interval18_different_cutoff_re\n"
perl 09_merge_qtl_factor_ratio_and_hotspot_factor_ratio_re.pl
echo -e "09_merge_qtl_factor_ratio_and_hotspot_factor_ratio_re\n"